train_data_dir = <put absolut path here>
output_dir = <put absolut path here>
logging_dir = <put absolut path here>
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
bucket_no_upscale = true
bucket_reso_steps = 64
caption_extension = ".txt"
enable_bucket = true
epoch = 20
gradient_accumulation_steps = 1
gradient_checkpointing = true
learning_rate = 0.0001
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_token_length = 75
max_train_epochs = 20
min_bucket_reso = 256
mixed_precision = "bf16"
network_dim = 256
network_module = "networks.lora"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False",]
optimizer_type = "Adafactor"
output_name = "test"
resolution = "512,512"
save_every_n_epochs = 5
save_model_as = "safetensors"
save_precision = "bf16"
seed = 20
text_encoder_lr = 0.0001
train_batch_size = 8
unet_lr = 0.0001
xformers = true
num_repeats = 20
